### ISSUE TITLE
Ctrl + A in the Manage history list should select all the displayed entries

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#74] opened 2019-12-31 23:11 UTC
Currently pressing Ctrl + A selects menu items and various other UI elements.

**Comment by stephanmahieu** [comment] 2020-01-01 15:14
There was also a bug regarding the Alt-key shortcuts not working (key being the underlined characters in the context-menu)

**Comment by stephanmahieu** [comment] 2020-01-10 15:51
Now fixed in release 2.5.0.0.

**Comment by wvxwxvw** [comment] 2020-01-11 01:34
@stephanmahieu 
I have everything left as it was.
![gif337](https://user-images.githubusercontent.com/13194155/72196769-9407d200-342b-11ea-8315-8e67bb9a740b.gif)

**Comment by stephanmahieu** [comment] 2020-01-11 16:24
Hmm, _works on my machine_.
Ctrl+A should not select all items in this list in this popup because you can select only 1 item but it should not highlight everything else.

Does it work in the the big popup window?

**Comment by wvxwxvw** [comment] 2020-01-12 00:38
68.4.1 esr x64. It's the same in the big window. Right away I'll check it on a clean profile.

**Comment by birdie-github** [comment] 2020-01-12 11:48
@wvxwxvw 

Works for me in the normal window - doesn't work in the popup window.

But then I'm running Firefox 72.

**Comment by wvxwxvw** [comment] 2020-01-12 12:35
@birdie-github А вы? =)

**Comment by birdie-github** [comment] 2020-01-12 13:19
Please stick to the English language and avoid offtopic comments. The author of this add-on doesn't have to handle SPAM in tickets.

**Comment by wvxwxvw** [comment] 2020-01-12 13:25
@birdie-github 
Please avoid offtopic comments. The author of this add-on doesn't deserve and doesn't have to handle SPAM in tickets. Like your previous one, about the extension version.

**Comment by stephanmahieu** [comment] 2020-01-12 15:52
Still can not reproduce this. Selected text is made invisible by manipulating the css style since the default behaviour can not be prevented.

I am running FF 72.0.1 (64 bit). Also with Quantum 73.0b3 (64-bits) no problem.

**Comment by stephanmahieu** [comment] 2020-01-12 15:59
Aha, does not work on Debian with FF 68.3.0esr (64bit).

Okay, will try to fix...

**Comment by stephanmahieu** [comment] 2020-01-12 17:41
Now fixed and available in v2.5.1.0

**Closed by stephanmahieu** 2020-01-12 17:41 UTC
Labels: enhancement

**Comment by wvxwxvw** [comment] 2020-01-13 01:14
All OK.
