### ISSUE TITLE
Phoronix.com forums/VBulletin 5.6.4 : nothing is saved

### ISSUE THREAD

**Issue by birdie-github** [stephanmahieu/formhistorycontrol-2#121] opened 2021-03-31 12:25 UTC
I'm using Firefox 87 for Linux and Form History Control doesn't save replies on this forum for some reasons.

I've temporarily switched back to Textarea Cache which works fine.

**Comment by shocked-gamer** [comment] 2021-04-01 11:16
i made an account to test it and i can confirm that when replying to posts it doesn't save the contents. however it saved my registration info so i guess the "reply" text box is coded differently from other normal ones.

**Comment by stephanmahieu** [comment] 2021-04-07 21:15
Testing also.
Hmm, I do see the updates being recorded while typing this. So it is recorded, maybe it disappears when I hit the comment button.

**Comment by stephanmahieu** [comment] 2021-04-07 21:22
In my case anything I type here is saved as type _textarea_.

Please make sure you have the [Miscellaneous preference](https://stephanmahieu.github.io/fhc-home/Manual/manual/#miscellaneous) "Retain which type of field" set correctly for this to work. Multi-line must be enabled.

**Comment by birdie-github** [comment] 2021-04-07 21:38
> In my case anything I type here is saved as type _textarea_.
> 
> Please make sure you have the [Miscellaneous preference](https://stephanmahieu.github.io/fhc-home/Manual/manual/#miscellaneous) "Retain which type of field" set correctly for this to work. Multi-line must be enabled.

Everything is enabled.

**Comment by shocked-gamer** [comment] 2021-04-08 13:59
birdie is talking about the phoronix forums, not github.

![Screenshot (59)](https://user-images.githubusercontent.com/33640073/114039856-c51fbe00-988b-11eb-9f8d-c6780f3e3922.png)

**Comment by stephanmahieu** [comment] 2021-04-09 22:15
The phoronix forums uses the [cke editor v5](https://ckeditor.com/).
This editor is also causing problems as mentioned in issue #103 No recovery of textbox - question2answer.
I still have to find a workaround for this wysiwyg editor.

**Comment by stephanmahieu** [comment] 2021-04-09 22:19
Duplicate of #103

**Comment by stephanmahieu** [comment] 2021-04-11 16:39
Issue is fixed in release 2.5.6.1 (released April 11 18:30 CET).

_This release will potentially also fix similar (wysiwyg-)editors using dynamically loaded iframe(s)._

**Closed by stephanmahieu** 2021-04-11 16:39 UTC
Labels: custom page handling
