### ISSUE TITLE
Remove icon from URL bar on Firefox

### ISSUE THREAD

**Issue by GameSpirit94** [stephanmahieu/formhistorycontrol-2#156] opened 2023-08-12 02:19 UTC
Hi,

Form History Control is an essential extension for me, so first of all : thank you.
My main browser is Firefox, and I also use Chrome, and I just want to ask if the extension can be as invisible on Firefox as it is on Chrome, what I mean is : can I have a box to check on Firefox to hide the icon extension that constantly appears in the URL bar ? It shows there by default and I can't find an option to disable it.

Thank you.

**Comment by stephanmahieu** [comment] 2023-08-13 23:00
It will be in the upcoming release very soon.

**Comment by stephanmahieu** [comment] 2023-10-08 13:04
Duplicate of #133

**Closed by stephanmahieu** 2023-10-08 13:04 UTC
Labels: duplicate

**Comment by GameSpirit94** [comment] 2023-10-09 02:52
Thank you !
