### ISSUE TITLE
FHC remembers only some text entered in Twitter's compose tweet box

### ISSUE THREAD

**Issue by axelsimon** [stephanmahieu/formhistorycontrol-2#63] opened 2019-12-09 11:03 UTC
Hi, the title is pretty self-explanatory:
when typing in tweets, especially when using twitter's "add tweet" function to send multiple tweets at once, FHC seems to only remember random tweets/text that was typed and misses lots of text.

Given that Twitter's current compose tweet box has a nasty tendency to crash and lose whatever was being typed, this is getting quite annoying :(

Thanks

**Comment by stephanmahieu** [comment] 2019-12-09 17:35
The cause is similar to issue #38, twitter (javascript) has only one edit field and its contents is moved the moment you select another message input box. This is perceived by the add-on as a regular update of a single edit field. This kind of behavior is impossible to detect by this or any other add-on, there is simply a too much javascript/dynamic-html magic going on under the hood of the website. With all this data shuffling and moving there is simply no way to determine what is really going on and what should be recorded and what not.

**Comment by stephanmahieu** [comment] 2021-04-19 08:58
Duplicate of #38

**Comment by stephanmahieu** [comment] 2021-04-19 08:58
The cause of this issue is the fact that when you have completed and published your message, the input field is emptied and prepared for the next message (tweet) you might want to publish. Because the input field remains the same, it is perceived by FHC as a regular update en the corresponding formhistory entry is updated accordingly.
More conversation type applications suffer from this very same behavior like for instance Twitter and WhatsApp Web.

I do not think this is really a serious issue given the fact that that the main purpose of storing formhistory (and that is especially the case for multiline fields), is saving it to protect you from loosing your hard work in  case disaster strucks. If you successfully published the message there is no longer a need for restoring the very same message.

I Also think that there is no viable solution for detecting the difference in emptying input field caused by normal user editing or successfully publishing a message.

**Closed by stephanmahieu** 2021-04-19 08:58 UTC
Labels: custom page handling
