### ISSUE TITLE
Still not showing content in popup windows on Linux

### ISSUE THREAD

**Issue by jidanni** [stephanmahieu/formhistorycontrol-2#5] opened 2018-01-20 17:23 UTC
![s](https://user-images.githubusercontent.com/1230959/35186078-59b15d0c-fe49-11e7-8999-d372a76eb966.jpg)

Package: firefox
Version: 58.0~b14-1
Debian Release: buster/sid
  APT prefers experimental
Architecture: amd64 (x86_64)
Kernel: Linux 4.14.0-3-amd64 (SMP w/2 CPU cores)
Locale: LANG=zh_TW.UTF-8, LC_CTYPE=zh_TW.UTF-8 (charmap=UTF-8), LANGUAGE=en_US:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/bash
Init: systemd (via /run/systemd/system)

Versions of packages firefox depends on:
ii  debianutils               4.8.4
ii  fontconfig                2.12.6-0.1
ii  libatk1.0-0               2.26.1-2
ii  libc6                     2.26.9000+20180108.401311cf-0experimental0
ii  libcairo-gobject2         1.15.8-3
ii  libcairo2                 1.15.8-3
ii  libdbus-1-3               1.12.2-1
ii  libdbus-glib-1-2          0.108-3
ii  libevent-2.1-6            2.1.8-stable-4
ii  libffi6                   3.3~20160224-1
ii  libfontconfig1            2.12.6-0.1
ii  libfreetype6              2.8.1-1
ii  libgcc1                   1:8-20180110-1
ii  libgdk-pixbuf2.0-0        2.36.11-1
ii  libglib2.0-0              2.55.1-1
ii  libgtk-3-0                3.22.26-2
ii  libgtk2.0-0               2.24.31-5
ii  libhunspell-1.6-0         1.6.2-1
ii  libjsoncpp1               1.7.4-3
ii  libnspr4                  2:4.16-1+b1
ii  libnss3                   2:3.34.1-1
ii  libpango-1.0-0            1.40.14-1
ii  libsqlite3-0              3.21.0-1
ii  libstartup-notification0  0.12-5
ii  libstdc++6                8-20180110-1
ii  libvpx4                   1.6.1-3
ii  libx11-6                  2:1.6.4-3
ii  libx11-xcb1               2:1.6.4-3
ii  libxcb-shm0               1.12-1
ii  libxcb1                   1.12-1
ii  libxcomposite1            1:0.4.4-2
ii  libxdamage1               1:1.1.4-3
ii  libxext6                  2:1.3.3-1+b2
ii  libxfixes3                1:5.0.3-1
ii  libxrender1               1:0.9.10-1
ii  libxt6                    1:1.1.5-1
ii  procps                    2:3.3.12-3
ii  zlib1g                    1:1.2.8.dfsg-5

firefox recommends no packages.

Versions of packages firefox suggests:
pn  fonts-lmodern          <none>
pn  fonts-stix | otf-stix  <none>
pn  libcanberra0           <none>
ii  libgssapi-krb5-2       1.16-1
pn  mozplugger             <none>

-- no debconf information

**Comment by jidanni** [comment] 2018-01-20 17:32
OK I found a workaround for the smaller window shown above:
1. Place the pointer somewhere within the window.
1. Right click.

**Comment by jidanni** [comment] 2018-01-20 17:39
Alas, for the "Manage History" window, although sweeping the pointer over the window back and forth reveals indeed there are things there, as the pointer changes from an arrow to a finger and back, but there is nothing we can do to actually see them. It is just one big blank screen.
Note I am using a rather fast laptop, not a slow system.

**Comment by stephanmahieu** [comment] 2018-01-21 14:31
Resizing the window should reveal the content.

I tried adding an automatic resize action after the window was displayed (as of version 2.0.2.5) of one pixel and that seemed to have fixed it for the majority of cases.
It only seems to occur on Linux OS, so it is probably some weird bug in Firefox.

I still have no clue whatsoever to what is causing this so I will investigate this further.

**Comment by davidhedlund** [comment] 2018-01-22 11:40
> I tried adding an automatic resize action after the window was displayed (as of version 2.0.2.5) of one pixel and that seemed to have fixed it for the majority of cases.

The windows are still blank in Form History Control 2.0.3.2 so your fix don't work. Can you please have a new look?

**Comment by davidhedlund** [comment] 2018-01-22 11:42
You asked by me email regarding this issue before:

> Do you experience this problem in linux and on older and/or slow hardware too?

Yes. my graphic driver: Gallium 0.4 on NVA8

**Comment by stephanmahieu** [comment] 2018-06-10 21:38
It is a bug in Firefox, see Bugzilla:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1425829
- https://bugzilla.mozilla.org/show_bug.cgi?id=1416505

**Comment by davidhedlund** [comment] 2018-06-10 21:40
Thank you for finding the cause of it.

**Comment by stephanmahieu** [comment] 2018-08-26 13:43
Closing this issue because it is a bug in the browser and it is not fixable in the application (also no effective workaround).

**Closed by stephanmahieu** 2018-08-26 13:43 UTC
